function [parGrid, dimParGrid] = paramGrid(NetPars)
% Generate parameter grid to scan the parameter space. 
% The grid is generated by using the fields in NetPars who has
% more than one COLUMN. 

% Wen-hao Zhang, Mar-22-2015

valuePar = [];
dimParGrid = struct('valuePar', [], 'namePar', [], ...
    'sizePar', []);

i = 1;
for fname = fieldnames(NetPars)'
    netpar = NetPars.(fname{1});
    if size(netpar, 2) > 1 && ~ischar(netpar)
        valuePar = [valuePar, {netpar}];
        
        dimParGrid(i).namePar = fname{1};
        dimParGrid(i).valuePar = netpar;
        dimParGrid(i).sizePar = size(netpar, 1);
        i = i + 1;
    end
end

if isempty(dimParGrid(1).valuePar)
    % only ONE parameter set
    parGrid = NetPars;
else    
    sizeGrid = cellfun(@(x) size(x, 2), valuePar);
    if length(sizeGrid) == 1
        sizeGrid = [sizeGrid, 1];
    end
    parGridStruct = repmat(NetPars, sizeGrid);
    
    Expr = [];
    for j = 1: length(valuePar)
        Expr = [Expr, 'sub{' num2str(j) '},'];
    end
    Expr = ['[' Expr(1:end-1), ']'];
    
    for iter = 1: prod(sizeGrid)
        eval([Expr '=ind2sub(sizeGrid, ' num2str(iter) ');']);       
        for j = 1: length(valuePar)
            parGridStruct(iter).(dimParGrid(j).namePar) = valuePar{j}(:, sub{j});
        end
    end
    
    parGrid = parGridStruct;
end
